"use es6";

export const APP_STARTED = "APP_STARTED";
export const INITIALIZE_AUTH = "INITIALIZE_AUTH";
export const CREATE_ALERT = "CREATE_ALERT";
export const HAS_ERROR = "HAS_ERROR";

export const REQUEST_CHANGE_COLUMN = "REQUEST_CHANGE_COLUMN";
export const RECEIVE_CHANGE_COLUMN = "RECEIVE_CHANGE_COLUMN";
export const FAIL_CHANGE_COLUMN_REQUEST = "FAIL_CHANGE_COLUMN_REQUEST";

export const REQUEST_UPDATE_COLUMN = "REQUEST_UPDATE_COLUMN";
export const RECEIVE_UPDATE_COLUMN = "RECEIVE_UPDATE_COLUMN";
export const FAIL_UPDATE_COLUMN_REQUEST = "FAIL_UPDATE_COLUMN_REQUEST";

export const REQUEST_UPDATE_CARD = "REQUEST_UPDATE_CARD";
export const RECEIVE_UPDATE_CARD = "RECEIVE_UPDATE_CARD";
export const FAIL_UPDATE_CARD_REQUEST = "FAIL_UPDATE_CARD_REQUEST";

export const REQUEST_BOARD_DETAIL = "REQUEST_BOARD_DETAIL";
export const RECEIVE_BOARD_DETAIL = "RECEIVE_BOARD_DETAIL";
export const FAIL_BOARD_DETAIL_REQUEST = "FAIL_BOARD_DETAIL_REQUEST";

export const REQUEST_UPDATE_BOARD = "REQUEST_UPDATE_BOARD";
export const RECEIVE_UPDATE_BOARD = "RECEIVE_UPDATE_BOARD";
export const FAIL_UPDATE_BOARD_REQUEST = "FAIL_UPDATE_BOARD_REQUEST";

export const REQUEST_BOARD_LIST = "REQUEST_BOARD_LIST";
export const RECEIVE_BOARD_LIST = "RECEIVE_BOARD_LIST";
export const FAIL_BOARD_LIST_REQUEST = "FAIL_BOARD_LIST_REQUEST";

export const REQUEST_CARD_DETAIL = "REQUEST_CARD_DETAIL";
export const RECEIVE_CARD_DETAIL = "RECEIVE_CARD_DETAIL";
export const FAIL_CARD_DETAIL_REQUEST = "FAIL_CARD_DETAIL_REQUEST";

export const REQUEST_NEW_BOARD = "REQUEST_NEW_BOARD";
export const RECEIVE_NEW_BOARD = "RECEIVE_NEW_BOARD";
export const FAIL_NEW_BOARD_REQUEST = "FAIL_NEW_BOARD_REQUEST";
